image: registry.hypriot.com/arm_base/dockerindocker
docker:
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
git:
  path: github.com/hypriot/rpi-alpine-scratch
script:
  - echo "+++++ start docker daemon +++++"
  - wrapdocker &
  - sleep 5
  - docker login --username=$$REGISTRY_USER --password=$$REGISTRY_PASSWORD --email=$$REGISTRY_USER_EMAIL $$REGISTRY_URL
  - echo "+++++ build docker image +++++"
  - make
  - echo "+++++ stop docker daemon +++++"
  - start-stop-daemon --stop --pidfile "/var/run/docker.pid"
  - echo -e "#####################\n***** COMPLETED *****\n#####################"
